>>> import turtle
>>> turtle.reset()
>>> turtle.left(30)
>>> turtle.forward(100)
>>> turtle.reset()
>>> turtle.left(60)
>>> turtle.forward(100)
>>> turtle.right(60)
>>> turtle.undo()
>>> turtle.right(120)
>>> turtle.forward(100)
>>> turtle.penup()
>>> turtle.goto(200,200)
>>> turtle.undo()
>>> turtle.goto(150,150)
>>> turtle.right(30)
>>> turtle.pendown()
>>> turtle.forward(200)
>>> turtle.penup()
>>> turtle.goto(50,30)
>>> turtle.undo()
>>> turtle.goto(50,-50)
>>> turtle.forward(50)
>>> turtle.undo()
>>> turtle.pendown()
>>> turtle.forward(50)
>>> turtle.left(90)
>>> turtle.forward(50)
>>> turtle.forward(100)
>>> turtle.penup()
>>> turtle.goto(100,0)
>>> turtle.undo()
>>> turtle.goto(300,70)
>>> turtle.goto(300,90)
>>> turtle.pendown()
>>> turtle.forward(70)
>>> turtle.penup()
>>> turtle.goto(300,90)
>>> turtle.right(90)
>>> turtle.pendown()
>>> turtle.forward(50)
>>> turte.right(90)
Traceback (most recent call last):
  File "<pyshell#41>", line 1, in <module>
    turte.right(90)
NameError: name 'turte' is not defined
>>> turtle.right(90)
>>> turtle.left(180)
>>> turtle.forward(70)
>>> turtle.forward(20)
>>> turtle.undo()
>>> turtle.penup()
>>> turtle.goto(335,40)
>>> turtle.pendown()
>>> turlte.right(90)
Traceback (most recent call last):
  File "<pyshell#50>", line 1, in <module>
    turlte.right(90)
NameError: name 'turlte' is not defined
>>> turtle.right(90)
>>> turtle.forward(40)
>>> turtle.left(90)
>>> turtle.penup()
>>> turtle.goto(380,0)
>>> turtle.left(180)
>>> turtle.pendown()
>>> turtle.forward(120)
>>> turtle.undo()
t
>>> 
>>> turtle.forward(110)
>>> turtle.penup()
>>> turtle.goto(335,-20)
>>> turtle.pendown()
>>> turtle.circle(50)
>>> turtle.penup()
>>> turtle.goto(400,90)
>>> turtle.goto(450,90)
>>> turtle.pendown()
>>> turtle.circle(50)
>>> turtle.penup()
>>> turtle.goto(480,70)
>>> turtle.got(550,70)
Traceback (most recent call last):
  File "<pyshell#73>", line 1, in <module>
    turtle.got(550,70)
AttributeError: module 'turtle' has no attribute 'got'
>>> turtle.goto(550,70)
>>> turtle.goto(550,90)
>>> turtle.goto(550,130)
>>> turtle.left(90)
>>> turtle.pendown()
>>> turtle.forward(200)
>>> turtle.penup()
>>> turtle.goto(550,70)
>>> turtle.right(90)
>>> turtle.pendown()
>>> turtle.forward(50)
>>> turtle.penup()
>>> turtle.goto(550,35)
>>> turtle.goto(550,20)
\
>>> turtl
Traceback (most recent call last):
  File "<pyshell#88>", line 1, in <module>
    turtl
NameError: name 'turtl' is not defined
>>> turtle.pendown()
>>> turtle.forward(50)
>>> turtle.penup()
>>> turtle.goto(450,-20)
>>> turtle.goto(450,-90)
>>> turtle.right(90)
>>> turtle.pendown()
>>> turtle.forward(90)
>>> turtle.undo()
>>> turtle.forward(70)
>>> turtle.penup()
>>> turtle.goto(450,-45)
>>> turtle.right(90)
>>> turtle.pendown()
>>> turtle.forward(50)
>>> turtle.penup()
>>> turtle.goto(500,-90)
>>> turtle.left(90)
>>> turtle.pendown()
>>> turtle.forward(70)
>>> turtle.penup()
>>> turtle.goto(500,-90)
>>> turtle.left(90)
>>> turtle.pendown()
>>> turtle.forward(50)
